### PR TITLE
Use specific lint ruleset version

### PR DESCRIPTION
**Pull request by hx-markterry**
#### What does this PR do? (please provide any background)

To stop the use case of our making

#### What tests does this PR have?

None extra

#### How can be this tested?

`npm test`, will run the linting rules on this project before the unit tests are run.

#### What gif best describes how you feel about this work?

giphy

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve run all the tests locally and they pass.

### CODE REVIEW

**Comment by pmcnr-hx** [comment]
Taking 2nd slot.

**Comment by pmcnr-hx** [comment]
:+1:

**Comment by hxoliverrumbelow** [comment]
This change adds a requirement of "You must have internet access (and GitHub must be up) in order to run tests. I'm not sure if that's acceptable?

```
(master)/repos/make-up$ npm test

> make-up@3.0.0 test /repos/make-up
> bin/make-up.js test && node_modules/.bin/istanbul cover node_modules/.bin/_mocha -- --recursive -R spec


/repos/make-up/bin/make-up.js:14
  if(error) throw error;
                  ^
Error: getaddrinfo ENOTFOUND
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16)
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

**Comment by hxoliverrumbelow** [comment]
Works great :+1:

**Pull request merged**
