### PR TITLE
Stop checking json

### PR DESCRIPTION
**Pull request by hx-markterry**
#### What does this PR do? (please provide any background)

This tool had a too lenient pattern match when searching for files to check, this work now only checks for .js and .jsx files.

#### What tests does this PR have?

New unit tests for the new glob pattern used.

#### How can this be tested?

1. Check out this project.
1. Create an `ignore.json` file in the root.
1. Create a 'find.jsx' file in the root.
1. Run `bin/make-up.js`
1. The files found will be printed, it should contain the jsx file but not the json file

#### Screenshots / Screencast
Output from my terminal during testing:

HX2069T1:make-up mark.terry$ bin/make-up.js 
Files:  [ './Gruntfile.js', './index.js' ]

HX2069T1:make-up mark.terry$ touch ignore.json
HX2069T1:make-up mark.terry$ bin/make-up.js 
Files:  [ './Gruntfile.js', './index.js' ]

HX2069T1:make-up mark.terry$ touch find.jsx
HX2069T1:make-up mark.terry$ bin/make-up.js 
Files:  [ './Gruntfile.js', './find.jsx', './index.js' ]

#### What gif best describes how you feel about this work?

oh-my-glob

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by philmeehan** [comment]
Taking dev

**Comment by philmeehan** [comment]
All working. Have also npm linked it from the repo I have moved to make-up 3 and it is now ignoring the json files that were giving me issues.

**Comment by hxjamesmcneil** [comment]
SE/Guru

**Comment by hxjamesmcneil** [comment]
:+1:

**Pull request merged**
