### PR TITLE
Changed SCSS Lint config to allow duplicate properties.

### PR DESCRIPTION
**Pull request by MCooke**
I feel we need to allow duplicate CSS properties. For example if we want to use rems for font-size then we should allow a fallback specificied in pixels. Another example would be using RGBA(0,0,0,.85) for font colours, we would need a hex fallback.

### CODE REVIEW

**Comment by david-hersey** [comment]
Makes sense to me, I'll +1

**Comment by lukefrake** [comment]
I don't think we should do this, I think we should ignore duplicate styles in the mixins file.
``` // scss-lint:disable DuplicateProperty ```
My reasoning for this is that when we are using fall backs they won't be forever, they are temporary to support older browsers, I don't want to let people accidentally duplicate styles for the sake of being able to handle older browsers.

**Comment by david-hersey** [comment]
But can we not strip out or revert the fallbacks as we drop support?

In the meantime if people duplicate we shoot em or fail their code review/PR?

**Comment by MCooke** [comment]
A few ways to skin this. I don't want to have to lint someones code during a code review.

Agree with Luke in this instance but think the linter should be more intelligent, similar to css-lint see here for more;
https://github.com/CSSLint/csslint/wiki/Disallow-duplicate-properties

**Pull request closed without merging**
