### PR TITLE
Fix date option

### PR DESCRIPTION
**Pull request by michaelcarter**
#### What does this PR do? (please provide any background)
Ensures that when there are no files that have been altered since a provided date, that the linting does not fail.

#### What tests does this PR have?
Updated existing unit tests

#### How can this be tested?
Run make-up on a folder containing JS files but provide a date option for the future. You should see the message `'No changes files since provided date. All ok.'`and the process should exit with 0.

#### What gif best describes how you feel about this work?
pleased

---
#### Developer Definition of Done/Quality Checklist (for PR author to complete BEFORE code review):
- [x] I have checked the [contributing document](../blob/master/CONTRIBUTING.md) and I'm happy for this to be reviewed.

#### Software Engineer or Developer review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

#### Software Engineer or project guru review:
- [x] I’ve witnessed the work behaving as expected (this could be on the authors machine or screencast).
- [x] I’ve checked for coding anti-patterns.
- [x] I’ve checked for appropriate test coverage.
- [x] I’ve checked all the tests are passing.

### CODE REVIEW

**Comment by robhuzzey** [comment]
Taking SE/DEV

**Comment by lukefrake** [comment]
Taking Guru and sounds solid to me :shipit:

**Comment by robhuzzey** [comment]
+1 from me

**Comment by hx-markterry** [comment]
ok with me :rocket:

**Pull request merged**
