### PR TITLE
Move to node 0.12

### PR DESCRIPTION
**Pull request by hx-markterry**
#### What does this PR do? (please provide any background)

Moving to node 0.12

#### What tests does this PR have?

None

#### How can this be tested?

Check CI

#### What gif best describes how you feel about this work?

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2**
- [x] :+1:

**Review 3**
- [x] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

### CODE REVIEW

**Comment by notABluesSinger** [comment]
Taken Slot 1️⃣

**Comment by pmcnr-hx** [comment]
Will we still make sure we're compatible with `node 0.10`? Can we run CI with different node versions?

**Comment by pmcnr-hx** [comment]
Good stuff: :+1:

**Comment by DuncanFenning** [comment]
Looks great 👍

**Pull request merged**
