### PR TITLE
Add mocha plugin for no-exclusive-tests

### PR DESCRIPTION
**Pull request by djbeaumont**
#### What does this PR do? (please provide any background)

Incorporates new eslint rules to prevent committing of `.only`'d tests.

#### What tests does this PR have?

Existing unit tests in make-up.

#### How can this be tested?

* `cd ~/git/hapi` or similar for your setup
* `rm .eslintrc` to allow the new config to be downloaded
* `npm run lint` and see that linting passes
* `npm install "make-up@git://github.com/holidayextras/make-up.git#f9fcfe0e7e6365d31343f57a55c68f3372c09d92" --save-dev` (commit of this PR)
* add `.only` to a test
* `npm test` and see that only your changed test runs
* `npm run lint` again and see that linting fails with something like `error  Unexpected exclusive mocha test  mocha/no-exclusive-tests`
* `git checkout package.json test/your/changed/spec.js` to revert your local changes to HAPI.

#### Screenshots / Screencast

N/A

#### What gif best describes how you feel about this work?

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by hx-markterry** [comment]
ok with me :sparkler:

**Comment by hx-markterry** [comment]
needs version bumps and changelog

**Comment by hxpaul** [comment]
Taking :two:

**Comment by hxpaul** [comment]
works for me :+1:

**Pull request merged**
